"""empty message

Revision ID: e8431c0e7b06
Revises: 0043ce87c440
Create Date: 2022-03-08 11:16:32.815483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8431c0e7b06'
down_revision = '0043ce87c440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
